# Generated by Django 3.0.5 on 2020-05-03 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_learning', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='type',
            field=models.CharField(choices=[('C', 'Chat')], default='C', max_length=1, verbose_name='TYPE'),
        ),
    ]
