# Generated by Django 3.0.5 on 2020-05-24 10:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('e_learning', '0003_auto_20200503_1410'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommended',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=30)),
                ('class_level', models.CharField(max_length=30)),
                ('book_title', models.CharField(max_length=30)),
                ('book_cover_image', models.ImageField(upload_to='')),
                ('attach_book', models.FileField(upload_to='')),
                ('recomended_by', models.CharField(max_length=30)),
                ('date_of_record', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
